version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm -version
      - npm run-script build
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
