version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - ls
      - pwd
      - yarn install
  build:
    commands:
      - pwd
      - yarn build
      - ls
artifacts:
  type: zip
  base-directory: 'build'
  paths:
    - '**/*'